name: Rust

on:
  push:
    tags: "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        rustup target add x86_64-unknown-linux-musl
        cargo build --release --target x86_64-unknown-linux-musl --manifest-path engine/Cargo.toml --release
    - name: Create release artifact
      run: |
        ls -al engine/target/x86_64-unknown-linux-musl/release
        cp engine/target/x86_64-unknown-linux-musl/release/zerofish zerofish_x86_64-linux
        ls -al
      env:
        CARGO_TARGET_DIR: engine/target/release
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: zerofish-linux
        path: zerofish_x86_64-linux
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        ls -l
        chmod +x zerofish_x86_64-linux
        mv zerofish_x86_64-linux zerofish-${tag_name}_x86_64-linux
        ls -al
        sha256sum zerofish-* > checksums.txt
        echo "$tag_name" > release_description.txt
        cat release_notes.md >> release_description.txt
        hub release create --draft \
                           -a "checksums.txt#Checksums" \
                           -a "zerofish-${tag_name}_x86_64-linux#Zerofish - Linux (x86_64)" \
                           -F release_description.txt "$tag_name"
