name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --manifest-path engine/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path engine/Cargo.toml
    - name: Create release artifact
      run: |
        mkdir -p release
        cp engine/target/release/zerofish release/zerofish
      env:
        CARGO_TARGET_DIR: engine/target/release
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        file_pattern: release/*      
